### ISSUE TITLE
Fails on Arch linux

### ISSUE THREAD

**Issue by Strykar** [shardul08/Google-Trend-Wallpaper#1]
```
$ ./updateWallpaper.sh 
Creating wallpaper...
Traceback (most recent call last):
  File "generateWallpaper.py", line 11, in <module>
    browser = webdriver.Firefox()
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Setting wallpaper...
/usr/bin/gsettings
```

**Comment by shardul08** [comment]
Is your firefox updated? What version are you using?

**Comment by Strykar** [comment]
That was the issue, thanks.
