### ISSUE TITLE
setup: "FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'"

### ISSUE THREAD

**Issue by sanderjo** [shardul08/Google-Trend-Wallpaper#5]
With geckodriver not yet installed, I got the hard core error below.

So why not put a try-except around `browser = webdriver.Firefox()` and exit on an except. 

I can send a PR if you want.

```
sander@witte:~/git/Google-Trend-Wallpaper$ ./setup.sh
Installing Python dependencies...
install ok installed
Installing Pillow...
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (5.4.1)
Creating wallpaper...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generateWallpaper.py", line 11, in <module>
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Setting wallpaper...
/usr/bin/gsettings
Setup successfully completed
sander@witte:~/git/Google-Trend-Wallpaper$
```

**Comment by shardul08** [comment]
Sure, I will merge the PR.

**Comment by sanderjo** [comment]
`

I have now this (see below). Not perfect, but better than the error.

Agree? If so, I'll send the PR
```
sander@witte:~/git/Google-Trend-Wallpaper$ ./updateWallpaper.sh 
Creating wallpaper...
Error: Install geckodriver, and make sure it's in your PATH
Setting wallpaper...
/usr/bin/gsettings
sander@witte:~/git/Google-Trend-Wallpaper$
```

**Comment by shardul08** [comment]
Looks good.

**Comment by shardul08** [comment]
Merged PR
