### ISSUE TITLE
Setting Country to PK fails

### ISSUE THREAD

**Issue by Strykar** [shardul08/Google-Trend-Wallpaper#7]
ISO 3166 country codes for India and Canada work, fails for Pakistan with:
```
$ ./updateWallpaper.sh 
Creating wallpaper...
Traceback (most recent call last):
  File "generateWallpaper.py", line 23, in <module>
    link_div = browser.find_element_by_xpath("/html/body/div[2]/div[2]/div/div[2]/div/div[{}]".format(k))
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[2]/div[2]/div/div[2]/div/div[2]

Setting wallpaper...
/usr/bin/gsettings
```

**Comment by shardul08** [comment]
Unfortunately the daily search trend data for Pakistan is not present in [Google Trends](https://trends.google.com/trends/trendingsearches/daily?geo=IN). That is why the code is not able to fetch the data and hence that error.
